import { useState } from 'react'
import { ArrowLeft, ArrowRight, Globe2, Users } from 'lucide-react'
import { getLanguage, withLanguage } from './language'
import './ApplicationReview.css'

const base = '/uis/'
const copy = {
  ms: { selector: ['PILIH KATEGORI PEMOHON', 'Anda Memohon Sebagai?', 'Pilih kategori untuk melihat saluran permohonan dan semakan yang berkaitan.'], change: 'Tukar Kategori', admission: 'Maklumat Kemasukan',
    groups: { malaysian: ['Malaysian', 'Pelajar Malaysia', 'Permohonan pengajian untuk program Asasi, Diploma, Sarjana Muda dan Pascasiswazah.', [['Pelajar Malaysia', 'Permohonan dan semakan bagi program Asasi, Diploma dan Ijazah Sarjana Muda.', 'mohon-semak-asasi-dip-ism.jpg', 'foundation'], ['Pelajar Malaysia', 'Permohonan dan semakan bagi program Sarjana Kerja Kursus.', 'mohon-semak-sarjana-kk.jpg', 'postgraduate'], ['Pelajar Malaysia', 'Permohonan dan semakan bagi program Sarjana Penyelidikan dan PhD.', 'mohon-semak-sarjana-phd.jpg', 'postgraduate']]], international: ['International', 'Pelajar Antarabangsa', 'Permohonan dan semakan untuk program Asasi, Diploma, Sarjana Muda, Sarjana dan PhD.', [['International Student', 'Permohonan dan semakan untuk program Asasi, Diploma, Sarjana Muda, Sarjana dan PhD.', 'mohon-semak-asasi-dip-ism-sarjana-int.jpg', 'foundation'], ['International Student', 'Permohonan dan semakan untuk program Sarjana dan PhD.', 'mohon-semak-sarjana-phd-int.jpg', 'postgraduate']]] } },
  en: { selector: ['APPLICATION PATHWAY', 'What are you applying as?', 'Choose a category to view the relevant application and review pathway.'], change: 'Change Category', admission: 'Admission Information',
    groups: { malaysian: ['Malaysian', 'Malaysian Students', 'Study applications for Foundation, Diploma, Bachelor and Postgraduate programmes.', [['Malaysian Students', 'Applications and reviews for Foundation, Diploma and Bachelor programmes.', 'mohon-semak-asasi-dip-ism.jpg', 'foundation'], ['Malaysian Students', 'Applications and reviews for taught Master programmes.', 'mohon-semak-sarjana-kk.jpg', 'postgraduate'], ['Malaysian Students', 'Applications and reviews for Research Master and PhD programmes.', 'mohon-semak-sarjana-phd.jpg', 'postgraduate']]], international: ['International', 'International Students', 'Application and review pathways for Foundation, Diploma, Bachelor, Master and PhD programmes.', [['International Students', 'Applications and reviews for Foundation, Diploma, Bachelor, Master and PhD programmes.', 'mohon-semak-asasi-dip-ism-sarjana-int.jpg', 'foundation'], ['International Students', 'Applications and reviews for Master and PhD programmes.', 'mohon-semak-sarjana-phd-int.jpg', 'postgraduate']]] } },
  zh: { selector: ['\u7533\u8bf7\u6e20\u9053', '\u60a8\u4ee5\u54ea\u79cd\u8eab\u4efd\u7533\u8bf7\uff1f', '\u8bf7\u9009\u62e9\u7c7b\u522b\u4ee5\u67e5\u770b\u76f8\u5173\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u6e20\u9053\u3002'], change: '\u66f4\u6362\u7c7b\u522b', admission: '\u5165\u5b66\u4fe1\u606f', groups: { malaysian: ['Malaysian', '\u9a6c\u6765\u897f\u4e9a\u5b66\u751f', '\u9002\u7528\u4e8e\u9884\u79d1\u3001\u6587\u51ed\u3001\u5b66\u58eb\u53ca\u7814\u7a76\u751f\u8bfe\u7a0b\u7684\u7533\u8bf7\u3002', [['\u9a6c\u6765\u897f\u4e9a\u5b66\u751f', '\u9884\u79d1\u3001\u6587\u51ed\u53ca\u5b66\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u3002', 'mohon-semak-asasi-dip-ism.jpg', 'foundation'], ['\u9a6c\u6765\u897f\u4e9a\u5b66\u751f', '\u6388\u8bfe\u578b\u7855\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u3002', 'mohon-semak-sarjana-kk.jpg', 'postgraduate'], ['\u9a6c\u6765\u897f\u4e9a\u5b66\u751f', '\u7814\u7a76\u578b\u7855\u58eb\u53ca\u535a\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u3002', 'mohon-semak-sarjana-phd.jpg', 'postgraduate']]], international: ['International', '\u56fd\u9645\u5b66\u751f', '\u9002\u7528\u4e8e\u9884\u79d1\u3001\u6587\u51ed\u3001\u5b66\u58eb\u3001\u7855\u58eb\u53ca\u535a\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u6e20\u9053\u3002', [['\u56fd\u9645\u5b66\u751f', '\u9884\u79d1\u3001\u6587\u51ed\u3001\u5b66\u58eb\u3001\u7855\u58eb\u53ca\u535a\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u3002', 'mohon-semak-asasi-dip-ism-sarjana-int.jpg', 'foundation'], ['\u56fd\u9645\u5b66\u751f', '\u7855\u58eb\u53ca\u535a\u58eb\u8bfe\u7a0b\u7684\u7533\u8bf7\u4e0e\u67e5\u8be2\u3002', 'mohon-semak-sarjana-phd-int.jpg', 'postgraduate']]] } },  ar: { selector: ['Arabic'], change: 'Change category', admission: 'Admission information', groups: { malaysian: ['Malaysian', 'Malaysian Students', 'Application pathway for Foundation, Diploma, Bachelor and postgraduate programmes.', [['Malaysian Students', 'Foundation, Diploma and Bachelor applications.', 'mohon-semak-asasi-dip-ism.jpg', 'foundation'], ['Malaysian Students', 'Taught Master applications.', 'mohon-semak-sarjana-kk.jpg', 'postgraduate'], ['Malaysian Students', 'Research Master and PhD applications.', 'mohon-semak-sarjana-phd.jpg', 'postgraduate']]], international: ['International', 'International Students', 'Application pathway for Foundation, Diploma, Bachelor, Master and PhD programmes.', [['International Students', 'Foundation, Diploma, Bachelor and postgraduate applications.', 'mohon-semak-asasi-dip-ism-sarjana-int.jpg', 'foundation'], ['International Students', 'Master and PhD applications.', 'mohon-semak-sarjana-phd-int.jpg', 'postgraduate']]] } },
}

export default function ApplicationReview({ language = getLanguage() }) {
  const [selectedGroup, setSelectedGroup] = useState(null)
  const text = copy[language] || copy.ms
  const selected = selectedGroup ? text.groups[selectedGroup] : null
  if (!selected) return <section className="applicant-selector" aria-labelledby="applicant-selector-title">
    <div className="applicant-selector-heading"><p>{text.selector[0]}</p><h2 id="applicant-selector-title">{text.selector[1]}</h2><span>{text.selector[2]}</span></div>
    <div className="applicant-choice-grid">{Object.entries(text.groups).map(([id, group]) => { const Icon = id === 'international' ? Globe2 : Users; return <button type="button" className="applicant-choice-card" key={id} onClick={() => setSelectedGroup(id)}><span className="applicant-choice-icon"><Icon size={29}/></span><span className="applicant-choice-copy"><strong>{group[0]}</strong><small>{group[1]}</small><span>{group[2]}</span></span><span className="applicant-choice-arrow"><ArrowRight size={19}/></span></button> })}</div>
  </section>
  return <section className="application-options">
    <div className="application-options-head"><div><p>{text.selector[0]}</p><h2>{selected[1]}</h2><span>{selected[2]}</span></div><button type="button" onClick={() => setSelectedGroup(null)}><ArrowLeft size={16}/> {text.change}</button></div>
    <div className="apply-grid">{selected[3].map(([title, description, image, level]) => <article className="apply-card" key={image}><img src={base + image} alt=""/><div><small>{title}</small><p>{description}</p><a className="orange-btn" href={withLanguage('/permohonan-semakan/' + selectedGroup + '?level=' + level, language)}>{text.admission} <ArrowRight size={15}/></a></div></article>)}</div>
  </section>
}